---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: manual-trigger-binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-trigger-listener
spec:
  triggers:
    - binding:
        name: manual-trigger-binding
      template:
        name: manual-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: manual-template
spec:
  params:
    - name: WORKSPACE_ID
      description: The workspace id
    - name: apikey
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: deploy-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: WORKSPACE_ID
            value: $(params.WORKSPACE_ID)
          - name: repository
            value: $(params.repository)